### ISSUE TITLE
[BUG] Random Location not synced between players

### ISSUE THREAD

**Issue by Nanorithm** [i-kulgu/ik-blackmarket#10]
It seems like when you use the random location feature, it is specific to the player. So say I have locations A and B, for me it could be at location A, but for another player it could be at location B. Is there any way to fix this? I just updated to the most recent update.

**Comment by PavilonGaming** [comment]
im having the same issue

**Comment by nzkfc** [comment]
@Nanorithm @PavilonGaming  this is now server-sided and fixed, so should be good to go :)

**Comment by i-kulgu** [comment]
As nzkfc said, it's fixed in the new release, please update your resource.

**Comment by Nanorithm** [comment]
Dang you beat me to it haha I just updated it myself but I hadn't gotten around to making a PR yet. Thanks!
