### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Deksodija** [i-kulgu/ik-blackmarket#4]
[script:ik-blackmarke] SCRIPT ERROR: @ik-blackmarket/server.lua:89: attempt to index a nil value (global 'info')

**Comment by Staticdevvv** [comment]
I get this error how to i fix it 

![image](https://user-images.githubusercontent.com/75772083/180072753-8e38d2b0-a8c2-4d58-a8c0-3785ca1b3ad9.png)

**Comment by i-kulgu** [comment]
> I get this error how to i fix it
> 
> ![image](https://user-images.githubusercontent.com/75772083/180072753-8e38d2b0-a8c2-4d58-a8c0-3785ca1b3ad9.png)

Change inside the config file where your images are. If you use qb-inventory then put that inside Config.img
