### ISSUE TITLE
server.lua:38: attempt to compare nil with number

### ISSUE THREAD

**Issue by NayeonIsTheKey** [i-kulgu/ik-blackmarket#7]
Required item needed is working, all locations working, items showing at the menu, the only problem is when I try to buy a weapon, it shows this error.

![image](https://user-images.githubusercontent.com/83680775/186405414-3c7fca86-03a9-4e0b-a9ab-8e31b252bdb5.png)

**Comment by i-kulgu** [comment]
This is fixed with the new version, please download and retry.
