### ISSUE TITLE
error when buying and item requirement

### ISSUE THREAD

**Issue by Luckyyang24** [i-kulgu/ik-blackmarket#8]
Running on the latest qbcore version

![image](https://user-images.githubusercontent.com/106300955/190937846-a238c32b-1efc-41e8-9bfa-7adb8d25419b.png)
 
Also when open with item is set to true, i can still access the black market without the item
![image](https://user-images.githubusercontent.com/106300955/190938651-bb3e7746-7835-407f-bc63-e998a4dcda9e.png)

![image](https://user-images.githubusercontent.com/106300955/190938711-1f92404c-1697-4d72-8b60-7ba0e81ae12e.png)

![image](https://user-images.githubusercontent.com/106300955/190938744-ee4217e3-667e-4fd8-8104-a2f79eebb2d7.png)

**Comment by i-kulgu** [comment]
Fixed with the new version, please update and retry.
